### ISSUE TITLE
Override craft version

### ISSUE THREAD

**Issue by brybeecher** [BlackPepperSoftware/docker-craftcms#1]
A nice feature would be to allow overriding the Craft version. Or allowing users to always pull the latest version. It is accessible via http://craftcms.com/latest.zip?accept_license=yes

That way its not dependent on this repository being up to date :)

**Comment by markhobson** [comment]
Hi, thanks for the feedback! I think having the Craft version explicitly specified in the Dockerfile is a good thing, as it gives us reproducible builds, but I agree it'd be nice to easily override. How about we introduce a Docker build argument to specify the version?

**Comment by brybeecher** [comment]
Any mechanism to control the version sounds good for me. Thanks so much for your work on this docker image!

**Comment by markhobson** [comment]
No probs, glad it's useful! I'll add some build args now and update the README.
