### ISSUE TITLE
Craft version via build args not working in docker-compose

### ISSUE THREAD

**Issue by sem4phor** [BlackPepperSoftware/docker-craftcms#8]
I tried to use the documented build args with dockker-compose like seen in the following config:

```
craft:
    depends_on:
      - db
    build:
      context: https://github.com/BlackPepperSoftware/docker-craftcms.git
      args:
        CRAFT_VERSION: '3.1'
        CRAFT_BUILD: '10'
```

In the docker logs i can see that the correct version 3.1.10 is downloaded when building the container. But when i start the container with docker compose up the version of craft is 3.1.8 (in composer and the admin interface)

Furthermore there are some errors occuring in step:
```
Step 8/15 : RUN wget https://download.craftcdn.com/craft/$CRAFT_VERSION/$CRAFT_ZIP -O /tmp/$CRAFT_ZIP     && unzip -q /tmp/$CRAFT_ZIP -d /var/www/ 	&& rm /tmp/$CRAFT_ZIP 	&& chmod +x /var/www/craft && sed -i "s/html/web/" /etc/apache2/sites-available/000-default.conf 	&& rm -r /var/www/html 	&& echo "php_value memory_limit 256M" >> /var/www/web/.htaccess 	&& service apache2 restart
 ---> Running in eff2539ecdc3
--2019-02-20 10:47:59--  https://download.craftcdn.com/craft/3.1/Craft-3.1.10.zip
Resolving download.craftcdn.com (download.craftcdn.com)... 23.111.9.67
Connecting to download.craftcdn.com (download.craftcdn.com)|23.111.9.67|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30470292 (29M) [application/zip]
Saving to: '/tmp/Craft-3.1.10.zip'
```

2019-02-20 10:48:03 (7.07 MB/s) - '/tmp/Craft-3.1.10.zip' saved [30470292/30470292]

The error/warning:
```
sh: 0: getcwd() failed: No such file or directory
Restarting Apache httpd web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
.
```

Can you provide a docker compose example where a craft specific verison is pinned?

**Comment by markhobson** [comment]
Hi there, I changed the demo compose file to build a different version as per your example and get a similar version mismatch:

```
version: '2.4'

services:
  
  site:
    build:
      context: https://github.com/BlackPepperSoftware/docker-craftcms.git
      args:
        CRAFT_VERSION: 3.0
        CRAFT_BUILD: 40
    environment:
      DB_SERVER: database
      DB_USER: craft
      DB_PASSWORD: password
      DB_DATABASE: craft
      DB_DRIVER: mysql
      CRAFT_SITE_URL: http://localhost:8080/
    links:
      - database
    ports:
      - "8080:80"

  database:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: craft
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: craft
    ports:
      - "3306:3306"
```

This reports 3.1.8 within the UI.

It looks like there's a problem with the Craft archive versions being out of sync with their content. I've raised an issue for this with Craft: https://github.com/craftcms/cms/issues/3871

I'll wait for a response from them before resolving this issue.

**Comment by sem4phor** [comment]
Hmm but in my case it shouldve worked.
The cdn url was https://download.craftcdn.com/craft/3.0/Craft-3.1.10.zip and when you download that and view the composer file of /vendor/craftcms then you see that the version is 3.1.10 (correct). But it is obviously not being used by the built docker container.

**Comment by markhobson** [comment]
I've tried that locally with the above docker-compose file and the UI reports 3.1.12. Are you destroying your database container in between runs? The UI displays the application version from the database, so if that's persisting across Craft version changes then it won't necessarily show what you'd expect.

You can query the application version in the database using:

```
SELECT version FROM craft_info;
```

**Comment by sem4phor** [comment]
yes it was my bad sorry :) so i . guess this can be closed

**Comment by markhobson** [comment]
Great, no problem, thanks for highlighting the mismatched archive versions!
